export const countryCodes = [
  { name: "대한민국", countryCode: "KOR" },
  { name: "미국", countryCode: "USA" },
  { name: "일본", countryCode: "JPN" },
  //   { name: "유로존(유럽연합)", countryCode: "EUU" },
  { name: "중국", countryCode: "CHN" },
  { name: "호주", countryCode: "AUS" },
  { name: "바레인", countryCode: "BHR" },
  { name: "홍콩", countryCode: "HKG" },
  { name: "싱가포르", countryCode: "SGP" },
  { name: "아랍에미리트", countryCode: "ARE" },
  { name: "영국", countryCode: "GBR" },
  { name: "말레이시아", countryCode: "MYS" },
  { name: "인도네시아", countryCode: "IDN" },
  { name: "がはこと", countryCode: "UTO" },
];
